### ISSUE TITLE
Neocities CLI broken on Debian 9.3

### ISSUE THREAD

**Issue by dotjax** [ungoldman/neocities-cli#2]
I've installed all the necessary gems, ran several updates and made sure Debian was up to date. This is the error I keep getting when I try to login.

`/var/lib/gems/2.3.0/gems/neocities-0.0.7/lib/neocities/cli.rb:70:in `run': undefined local variable or method `resp' for #<Neocities::CLI:0x0055adfb325ee8> (NameError)
Did you mean?  res`
`from /var/lib/gems/2.3.0/gems/neocities-0.0.7/bin/neocities:4:in '<top (required)>'`
`from /usr/local/bin/neocities:22:in 'load'
from /usr/local/bin/neocities:22:in '<main>'`

Not sure how to fix it? 

Ruby is 2.3.0
Neocities is 0.0.7

**Comment by ungoldman** [comment]
Hi @mknepper!

I think you're looking for a different repo: https://github.com/neocities/neocities-ruby

This repo is just an experimental CLI for Node.js that was never published.

I believe @kyledrake is the maintainer for that project.

**Comment by dotjax** [comment]
Thanks!
